### ISSUE TITLE
Have you ever meet the question that odomertry got from rf2o drifts?

### ISSUE THREAD

**Issue by Octalivia** [Hypha-ROS/hypha-racecar#10]
When the racecar have a greater acceleration to speed up or brake, the odometry will drift even when it is still after applying the brake. So I check the odometry got from rf2o, and it drifts. I wonder have you ever met this problem and how to deal with it?

**Comment by Octalivia** [comment]
I think that the problem is not because of rf2o. I found it worked well when drifting, maybe the reason is the AMCL location lost

**Comment by haochihlin** [comment]
Hi @Octalivia,
Thanks for being interested in this project.
About the drifting issue, based on my understanding, it has several causes:
1. The constant speed assumption held by rf2o: 
In the paper of rf2o, it assumed there is no sudden acceleration changes. We have tested it in quick accelerate/de-accelerate situation, the drifts of odometry outputs could be observed easily.

The best way to solve it is to add wheel odometry (encoder based). So this is why we launched the other project called "HyphaROS-minicar". Since the new platform provides wheel odometry which make us be able to implement advanced controller on it (e.g. 2 layers MPC)

Or you can use state-of-art VIO(e.g. ROVIO, SVO, etc) to replace laser based odometry.

2. The parameters (or performance) of AMCL:
Because the "HyphaROS-racecar" project was launched almost two years ago without recent updates. If I don't remember wrong, the parameters tuning of amcl in this repo was not the optimal ones. You can take the updated (fine-tuned one) parameters from "HyphaROS-minicar".

The other potential solution would be, again, using VIO for localization (e.g. ROVIOLI)

Cheers,
HaoChih, Lin

**Comment by Octalivia** [comment]
Thank u @haochihlin 
I aprreciate the information and advice you have provided. The problem was partially resolved by changing the amcl.launch.xml. Although particle cloud dispersion still happens after the brake, the odom doesn't drift like it used to be.   I will optimize the parameters to make it better. By the way, the documents have mentioned the speed of the racecar is up to 3m/s. Is it encoder-based or not？
Best regards,
Octalivia

**Comment by haochihlin** [comment]
Yes, the video you saw in the readme was based on rf2o odometry.

**Comment by Octalivia** [comment]
The amcl parameters only helps when rotating. I found the velocity from rf20 is 0 after the brake, but the odometry filtered by ekf publish that its velocity is still 1.5 m/s. Is seems the ekf is the reason. I'm sorry that I asked a wrong question.
