### ISSUE TITLE
Catkin_make error

### ISSUE THREAD

**Issue by speronig** [Hypha-ROS/hypha-racecar#16]
hi when i try to run the catkin_make comand at the end of the 'Initial Settings' page in the tutorial, I get this error:

![7](https://user-images.githubusercontent.com/49005827/57039497-c6212d00-6c2a-11e9-9f7c-55d3c443322e.PNG)

any help?

**Comment by speronig** [comment]
also I'm getting this error:

/home/giambo/catkin_ws/src/mapir-ros-pkgs/src/rf2o_laser_odometry/src/CLaserOdometry2D.cpp:900:29: error: no match for ‘operator+’ (operand types are ‘mrpt::poses::CPose3D’ and ‘mrpt::poses::CPose2D’)
     laser_pose = laser_pose + pose_aux_2D;

which i think it is where it all starts

**Comment by haochihlin** [comment]
Hi
The error seems came from rf2o_laser_odometry.
In this repo, we used an early version of rf2o_laser_odometry, which has some bugs insides.
Therefore, we add some patches in the forked folder.
You can find the fixed file as below:
https://github.com/Hypha-ROS/hypharos_racecar/tree/ver.1-release/document/replace_files/rf2o

Please find the "Document Replacement" on page 13 of the tutorial:
https://github.com/Hypha-ROS/hypharos_racecar/blob/ver.1-release/document/Hypha-ROS-RaceCar-Tutorial_V1.1.pdf

**Comment by leizhao3** [comment]
Hi All, I also encountered the same issue when I was trying to catkin_make Hypharos_racecar recently. Here is my solution & it works out for me:

Step 1: Copy all other files to catkin_ws/src, followed by the code below:
`
~catkin_ws/src: git clone https://github.com/MAPIRlab/rf2o_laser_odometry # Not from "https://github.com/MAPIRlab/mapir-ros-pkgs.git" from the documents since that repo is retired.
~catkin_ws/src: cd ..
~catkin_ws: catkin_make
`

Step 2: Document replacement as mentioned by @haochihlin 

Step 3: Rebuild the workspace again:
`~catkin_ws: catkin_make`
