### ISSUE TITLE
The name of brushed motor and ESC issue

### ISSUE THREAD

**Issue by zanpozane** [Hypha-ROS/hypha-racecar#21]
Hello! So now i try to make and build race car V.1 based on your tutorial workshop. I want to ask,  i have ESC TBLE-02S before but the motor can't move forward (just backward, right, and left).  When i tried to troubleshoot, then the ESC broken and burned inside. So do you know what happen and why? 
And By the way what is your brushed motor name and type that you used?

**Comment by haochihlin** [comment]
Hi @zanpozane ,
For TBLE-02S ESC, I suggest you to read the its official documentation directly.
(there are different mode: brushed or brushless)
Since you are using the brushed motor, you can just simply change the motor wires....

For the brushed motor, we used the default one in the TAMIYA car kit.
